Sb scraper
NovelTorpedo/noveltorpedo pull request #1
Opened 2017-02-08 02:24 UTC by popescu2

Mostly working Spacebattles scraper. Request to merge to master so video can be made showing both scrapers work.

2017-02-10 01:29 UTC, relsqui requested changes
GJ! Will work on updating the Tumblr bits myself and touch base again later this week.

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/items.py
> +# http://doc.scrapy.org/en/latest/topics/items.html
We probably don't need the above comments in this file, do we?

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/items.py
> +    nsfw_flag = scrapy.Field()
Are you using this flag?

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/middlewares.py
> +# http://doc.scrapy.org/en/latest/topics/spider-middleware.html
See previous comment about this comment block (I won't say this on every file, I promise, just this last one).

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +        # urls_stories is a touple with a url, and a corresponding Story object
"tuple," fwiw

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +        """ Scan the threads on a page
Reminding you that you wanted to update this docstring (and maybe do a pass at other docstrings).

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +            # change this to make sure that an author+host is unique
Punt this to future work! :)

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +                # yield scrapy.Request(thread_link, callback=self.scan_thread)
?

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +        segments, and links them to a story. (django models)
A+ specificity here

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +                # TODO ^^ Convert date time to actual date_time type
Time zones wooo. (Feel free to poke the Tumblr scraper to see how to add them, and/or ask me.)

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +
Roomy! But probably unnecessary whitespace. ;)

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +                # print("content: {0}".format(content[0:200]))
I suspect these are suppose to either both be commented or both be uncommented.

2017-02-10 01:29 UTC, relsqui commented on scrapers/Spacebattles/readme.md
> +Start up elasticsearch and database. (instructions in the website readme)
You can put an actual (relative) link here; see the main page readme for an example.

2017-02-11 00:56 UTC, popescu2 commented on scrapers/Spacebattles/Spacebattles/items.py
> +    nsfw_flag = scrapy.Field()
Ah, that code is deprecated.

2017-02-11 00:56 UTC, popescu2 commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +                # yield scrapy.Request(thread_link, callback=self.scan_thread)
Old code. Removed in latest commit

2017-02-11 00:56 UTC, popescu2 commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +                # TODO ^^ Convert date time to actual date_time type
Also fixed!

2017-02-11 00:57 UTC, popescu2 commented on scrapers/Spacebattles/Spacebattles/spiders/spacebattles_scraper.py
> +                # print("content: {0}".format(content[0:200]))
For debugging, it's not always necessary to print out so much text from a story. :/

2017-02-11 03:59 UTC, merged